import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "@/header/header";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <div className="">{children}</div>
        {/* <Footer/> */}
      </body>
    </html>
  );
}
